os:
  - linux
  - osx

dist: trusty
sudo: false

language: node_js

node_js:
  - 10

install:
  - npm install

script:
  - npm test
  - npm run prebuild-node
  - npm run prebuild-node-ia32
  - npm run prebuild-electron
  - npm run prebuild-electron-ia32
  - if [ "$TRAVIS_TAG" ]; then npm run upload; fi
