os: Visual Studio 2017

install:
  - ps: Install-Product node 10 x64
  - npm install

build_script:
  - npm test
  - npm run prebuild-node
  - npm run prebuild-node-ia32
  - npm run prebuild-electron
  - npm run prebuild-electron-ia32
  - if defined APPVEYOR_REPO_TAG_NAME (npm run upload)

test: off
